networks:
  proxy:
    name: proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1

services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy:1.3-alpine
    networks:
      proxy:
        ipv4_address: 172.31.0.10
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=America/Sao_Paulo
      - HTTPS_METHOD=noredirect
      - HSTS=off
      - update=2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d

  whoami:
    container_name: whoami
    # curl -H "Host: whoami.example.com" http://172.31.0.10 -k
    # curl -H "Host: test.example.com" https://172.31.0.10 -k
    networks:
      - proxy
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.example.com,test.example.com
      - CERT_NAME=default