kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # sed 's/0.0.0.0/127.0.0.1/g' -i ~/.kube/config
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  ipFamily: ipv4
  dnsSearch: []
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        authorization-mode: "Node,RBAC"
      certSANs:
      - "127.0.0.1"
      - "172.31.0.1"
      - "172.30.0.1"
      - "172.29.0.1"
      - "172.17.0.1"
      - "192.168.122.1"
      - "docker"
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:32000"]
    endpoint = ["http://localhost:32000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.example.com"]
    endpoint = ["http://registry.example.com"]